version: '3'

services:
  scrapy:
    build: .
    depends_on:
      - mongodb
      - spark
    environment:
      - MONGO_URI=mongodb://mongodb:27017/goodreads_db
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - mynetwork
    command: scrapy crawl goodreads_spider

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

  spark:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - mynetwork
    volumes:
      - ./spark:/opt/spark

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark
    networks:
      - mynetwork
    volumes:
      - ./spark:/opt/spark

networks:
  mynetwork:

volumes:
  mongo_data:
